language: python

python:
  - "2.7"
  - "pypy"
  - "3.4"
  - "3.5"
  - "3.6"

env:
  - SENTRY_PYTHON_TEST_POSTGRES_USER=postgres SENTRY_PYTHON_TEST_POSTGRES_NAME=travis_ci_test

cache:
  pip: true
  cargo: true

branches:
  only:
    - master
    - /^release\/.+$/

matrix:
  allow_failures:
    - python: "3.8-dev"

  include:
    - python: "3.7"
      dist: xenial
    - python: "3.8-dev"
      dist: xenial

    - name: Linting
      python: "3.6"
      install:
        - pip install tox
      script: tox -e linters
    - python: "3.6"
      name: Distribution packages
      install: false
      script: make travis-upload-dist
    - python: "3.6"
      name: Build documentation
      install: false
      script: make travis-upload-docs

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -c 'create database test_travis_ci_test;' -U postgres

services:
  - postgresql

install:
  - pip install tox
  - pip install codecov
  - bash scripts/download-semaphore.sh

script:
  - coverage erase
  - ./scripts/runtox.sh '' --cov=sentry_sdk --cov-report= --cov-branch
  - codecov --file .coverage*

notifications:
  webhooks:
    urls:
      - https://zeus.ci/hooks/7ebb3060-90d8-11e8-aa04-0a580a282e07/public/provider/travis/webhook
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
